services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.

    Parallalax\ApiClientBundle\Controller\:
        resource: '../../Controller/'
        tags: [ 'controller.service_arguments' ]